export const MenuCardDatas = [
    {
        id: 1,
        image: "/kingfood-img-icon/menu1.svg",
        title: "Lẩu bò vị Thái",
        desc: "Lẩu 2 ngăn",
        money: "1.300.000",
        rate: "4.2",
        status: "Tạm dừng",
        time: "10 phút",
        percent: "10% OFF",
    },
    {
        id: 2,
        image: "/kingfood-img-icon/menu2.svg",
        title: "Lẩu cua sông",
        desc: "Lẩu 2 ngăn",
        money: "1.200.000",
        rate: "4.2",
        status: "Sẵn sàng",
        time: "10 phút",
        percent: "20% OFF",
    },
    {
        id: 3,
        image: "/kingfood-img-icon/menu3.svg",
        title: "Burger King",
        desc: "Đồ ăn nhanh",
        money: "55.000",
        rate: "4.2",
        status: "Sẵn sàng",
        time: "15 phút",
        percent: "50% OFF",
    },
    {
        id: 4,
        image: "/kingfood-img-icon/menu4.svg",
        title: "Dom Perignon Vintage 2002",
        desc: "Đồ uống",
        money: "11.100.000",
        rate: "4.2",
        status: "Sẵn sàng",
        time: "5 phút",
        percent: "10% OFF",
    },
    {
        id: 5,
        image: "/kingfood-img-icon/menu5.svg",
        title: "Combo 6 người",
        desc: "Combo",
        money: "1.500.000",
        rate: "4.2",
        status: "Sẵn sàng",
        time: "10 phút",
        percent: "20% OFF",
    },
    {
        id: 6,
        image: "/kingfood-img-icon/menu6.svg",
        title: "Nhân lẩu bò thập cẩm",
        desc: "Đồ nhúng lẩu",
        money: "345.000",
        rate: "4.2",
        status: "Sẵn sàng",
        time: "15 phút",
        percent: "50% OFF",
    },
    {
        id: 7,
        image: "/kingfood-img-icon/menu7.svg",
        title: "Thịt bò giang Mỹ nhúng lẩu",
        desc: "Đồ nhúng lẩu",
        money: "1.300.000",
        rate: "4.2",
        status: "Tạm dừng",
        time: "10 phút",
        percent: "10% OFF",
    },
    {
        id: 8,
        image: "/kingfood-img-icon/menu8.svg",
        title: "Combo 7 người",
        desc: "Combo",
        money: "1.700.000",
        rate: "4.2",
        status: "Sẵn sàng",
        time: "10 phút",
        percent: "20% OFF",
    },
    {
        id: 9,
        image: "/kingfood-img-icon/menu9.svg",
        title: "Dom Perignon Vintage 2012",
        desc: "Đồ uống",
        money: "6.678.940",
        rate: "4.5",
        status: "Sẵn sàng",
        time: "5 phút",
        percent: "50% OFF",
    },
    {
        id: 10,
        image: "/kingfood-img-icon/menu10.svg",
        title: "Cristal Champagne Brut 2014",
        desc: "Đồ uống",
        money: "10.514.500",
        rate: "4.2",
        status: "Tạm dừng",
        time: "10 phút",
        percent: "10% OFF",
    },
    {
        id: 11,
        image: "/kingfood-img-icon/menu11.svg",
        title: "Lẩu cua sông",
        desc: "Lẩu 2 ngăn",
        money: "1.200.000",
        rate: "4.2",
        status: "Sẵn sàng",
        time: "10 phút",
        percent: "20% OFF",
    },
    {
        id: 12,
        image: "/kingfood-img-icon/menu12.svg",
        title: "Món cuốn tôm thịt",
        desc: "Bánh tráng cuốn",
        money: "200.000",
        rate: "4.7",
        status: "Sẵn sàng",
        time: "15 phút",
        percent: "50% OFF",
    },
]